language: rust
rust: nightly
script:
  - (cd src/ui && npm test)
  - cargo test
  - cargo test -- --ignored
env:
  global:
    - PGUSER=pgblackboard_test_user
    - PGPASSWORD=pgblackboard_test_pwd
    - PGHOST=localhost
    - PGPORT=5432
jdk:
  - openjdk7
before_script:
  - psql -c "CREATE USER $PGUSER WITH SUPERUSER LOGIN PASSWORD $PGPASSWORD;" -U postgres
