language: rust
rust: nightly
script: "cargo test && (cd src/ui && npm test)"
jdk:
    - openjdk7
before_script:
  - psql -c "create user pgblackboard_test_user with superuser login password 'pgblackboard_test_pwd';" -U postgres
