sudo: required
services:
  - docker
language: c
script:
  - echo 'ok'
after_success:
  - make && \
    docker build --tag exedealer/pgblackboard . && \
    docker login -u='$DOCKERHUB_USERID' -p='$DOCKERHUB_PASSWORD' && \
    docker push exedealer/pgblackbord

