sudo: required
services:
  - docker
after_success:
  - make;
    docker build --tag exedealer/pgblackboard .;
    docker login -u="$DOCKERHUB_USERID" -p="$DOCKERHUB_PASSWORD";
    docker push exedealer/pgblackbord;

