sudo: required
services:
  - docker
language: rust
node_js: 8
install:
  - mkdir -p ui/_dist
  - npm install
  - cargo fetch
script:
  - npm run build
  - cargo build --release --features uibuild
  - docker build --tag exedealer/pgblackboard .
after_success:
  - docker login -u $DOCKERHUB_USERID -p $DOCKERHUB_PASSWORD
  - docker push exedealer/pgblackboard

