[project]
name = "pgblackboard"
version = "0.2.0"
authors = ["exe-dealer <exe-dealer@yandex.ru>"]
build = "ui/build.rs"

[dependencies]
argparse = "0.2"
rustc-serialize = "0.3"
threadpool = "0.1.3"
# flate2 = "0.2.6"

[[bin]]
name = "pgblackboard"
path = "server/main.rs"
