[package]

name = "pgblackboard"
version = "0.2.0"
authors = ["exe-dealer <exe-dealer@yandex.ru>"]

[dependencies]
regex_macros = "*"
regex = "*"
rustc-serialize = "*"
byteorder = "*"
rust-crypto = "*"
