[package]
name = "pgblackboard"
version = "0.2.0"
authors = ["exe-dealer <exe-dealer@yandex.ru>"]
build = "build.rs"

[dependencies.postgres]
path = "./src/postgres"

[dependencies]
argparse = "0.1"
regex = "0.1.8"
regex_macros = "0.1.8"
rustc-serialize = "0.3"
threadpool = "0.1.3"
flate2 = "0.2.6"
