[package]

name = "pgblackboard"
version = "0.2.0"
authors = ["exe-dealer <exe-dealer@yandex.ru>"]

[dependencies.http]
path = "./src/http"

[dependencies]
#regex_macros = "*"
#regex = "*"
rustc-serialize = "0.3"
#byteorder = "*"
#rust-crypto = "*"
