version: '3'
services:
  pgblackboard:
    build:
      context: .
      args:
        CARGO_ARGS: ''
    environment:
      PGBB_POSTGRES: postgres:5432
    ports:
      - 7890:7890
    volumes:
      - ./ui:/opt/pgblackboard/ui:ro

  postgres:
    image: postgres:12-alpine # mdillon/postgis:11-alpine
    volumes:
      - ./demo.sql:/docker-entrypoint-initdb.d/demo.sql
