version: '3'
services:
  pgblackboard:
    build:
      context: .
      args:
        CARGO_ARGS: ''
    environment:
      PGBB_POSTGRES: 192.168.55.116:5433
    ports:
      - 7890:7890
    volumes:
      - ./ui:/opt/pgblackboard/ui:ro
  # postgres:
  #   image: mdillon/postgis:10-alpine
  #   volumes:
  #     - ./demo.sql:/docker-entrypoint-initdb.d/demo.sql
