[package]
name = "pgblackboard"
version = "0.2.0"
authors = ["exe-dealer <exe-dealer@yandex.ru>"]

[dependencies.postgres]
path = "./src/postgres"

[dependencies.http]
path = "./src/http"

[dependencies]
argparse = "0.1"
regex = "0.1"
regex_macros = "0.1"
rustc-serialize = "0.3"
flate2 = "0.2.6"

