[package]
name = "postgres"
version = "0.0.1"

[lib]
name = "postgres"
path = "lib.rs"
doctest = false

[dependencies]
rustc-serialize = "0.3"
byteorder = "0.3.8"
# rust-crypto = "0.2.31"

[dependencies.rust-md5]
git = "https://github.com/exe-dealer/rust-md5.git"
