[package]
name = "postgres"
version = "0.0.1"

[lib]
name = "postgres"
path = "lib.rs"
doctest = false

[[bin]]
name = "pgmsg"
path = "lib.rs"
doctest = false
test = false


[dependencies]
rustc-serialize = "0.3"
